name: Daily update
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      checks: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check traversal release
      id: check
      uses: pozetronic/github-action-get-latest-release@master
      with:
        owner: byrdocs
        repo: byrdocs-WikiCrawler
    - name: Download traversal
      run: |
        wget https://github.com/byrdocs/byrdocs-WikiCrawler/releases/download/${{ steps.check.outputs.release }}/traversal
        chmod 777 traversal
    - name: Run traversal
      shell: bash
      env:
        WIKI_SITE_URL: ${{ secrets.WIKI_SITE_URL }}
        WIKI_SITE_TOKEN: ${{ secrets.WIKI_SITE_TOKEN }}
      run: |
        traversal
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
      with:
        limit-access-to-actor: true
    - name: Upload to R2
      uses: ryand56/r2-upload-action@latest
      with:
        r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
        r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
        r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        r2-bucket: ${{ secrets.R2_DATA_BUCKET }}
        source-dir: output/
        destination-dir: ./
